modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "fof"
version = "1.1-SNAPSHOT"
displayName = "Forge of Fiends"
authors = "PheonixVX, -TheSirBatman-"
description = ''''''
#logoFile = ""

[[dependencies.fof]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fof]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fof]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"