    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 14
        java-version: 8
    - name: fetch fof
      uses: actions/checkout@v2
      with:
        repository: 'PheonixVX/fof'
        path: 'fof'
    - name: fof publishToMavenLocal
      run: cd ./fof && ./gradlew publishToMavenLocal && cd ..
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle